### ISSUE TITLE
deepExtend Transforms Arrays to Objects

### ISSUE THREAD

**Issue by TannerJepsen** [HelpfulHuman/Portals#19]
The deepExtend method used by the mergeGlobalsRequestInterceptor has an undesirable side effect of changing arrays to objects. For example, give the following as the data attribute of the options object:

{ "something" : [ "a", "b", "c" ] }

Will be changed to the following when using the mergeGlobalsRequestInterceptor:

{ "something" : { "0" : "a", "1", "b", "2", "c" } }

The deepExtend method should be changed to keep arrays as arrays.

**Comment by NickGlenn** [comment]
Thanks @TannerJepsen, I'll look into this as soon as possible.

**Comment by TannerJepsen** [comment]
Look good, thanks, Nick!
